"""Initial migration

Revision ID: 15b478ab8cc6
Revises: 8c53fad8b991
Create Date: 2025-05-18 22:58:45.650561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15b478ab8cc6'
down_revision = '8c53fad8b991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.drop_index('invoice')

    op.drop_table('customer_order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('admin')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])
        batch_op.drop_column('profile')
        batch_op.drop_column('name')
        batch_op.drop_column('contact')
        batch_op.drop_column('date_created')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=True))
        batch_op.drop_index('email')
        batch_op.drop_index('phone')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('salary')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('profile', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('profile', mysql.VARCHAR(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('profile', mysql.VARCHAR(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('customer_order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('orders', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.create_index('invoice', ['invoice'], unique=True)

    # ### end Alembic commands ###
