"""Upgrade db

Revision ID: 8c53fad8b991
Revises: 7cd6da5e8e3d
Create Date: 2025-05-11 16:45:34.356529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c53fad8b991'
down_revision = '7cd6da5e8e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
